"""Mirrors Section_Marketing/CustEnquiryRegister.aspx.vb and
CustEnquiryStatus.aspx.vb ("Lead Pending Status").

CustEnquiryRegister's Angular rebuild previously diverged from the source: the
source only ever shows ONE customer's enquiry (search-driven — 5 radio-button
modes resolve to a single CustID, then `webproc_showenquiry` fills both a
"Customer Information" panel and the grid for that customer only), but the
Angular page had been simplified to a full scrollable register with no
customer search. `/search` below restores the original single-customer,
search-driven flow (reusing the `/rows` query body with a CustID filter
instead of calling `webproc_showenquiry` directly — its full `E.*` column set
isn't confirmed 1:1, whereas this SELECT already is). `/rows` itself is kept
(now with an optional `cust_id` filter) since nothing about removing the
all-customers view was requested. IntroducedBy/ReferredBy/Campaign/
CurrentSoftware/CaseType are only partially populated from what Web_Enquiry
actually stores (best-effort, not all fields have a confirmed real source
column).

The WhatsApp "send" button calls `Proc_DripSendWhatsApp`, which sends a
real outbound WhatsApp message — same category of hazard as Section_General's
leave-workflow email/WhatsApp calls (see [[feedback_report_engine_simplification]]-
adjacent memory). Stubbed here (no actual send) rather than re-asking, per the
established default for this category of side effect.
"""

from fastapi import APIRouter
from pydantic import BaseModel

from app.db import get_cursor, rows_to_dicts

router = APIRouter(prefix="/marketing/register", tags=["marketing-register"])

_ROWS_SELECT = """
    SELECT {top}E.CustID, E.EnquiryDate, ISNULL(S.StagePercent, 0) AS StagePercent,
           ISNULL(UM.Name, '') AS ReceivedByName, E.Narration, ISNULL(S.SegmentName, '') AS SegmentName,
           ISNULL(NB.MasterValue, '') AS BusinessNatureName, ISNULL(ST.MasterValue, '') AS SourceTypeName,
           E.SourceNarration, ISNULL(IB.Name, '') AS IntroducedByName, ISNULL(RC.DisplayName, '') AS ReferredByName,
           ISNULL(CM.MasterValue, '') AS CampaignName, E.HardwarePatner,
           CASE WHEN E.AutoGenerated = 1 THEN 'Auto' ELSE 'New' END AS CaseType
    FROM Web_Enquiry E
    LEFT JOIN vwWebEnquiry_Status S ON S.CustID = E.CustID
    LEFT JOIN UserMaster UM ON UM.UserID = E.ReceivedBy
    LEFT JOIN Web_LittleMaster NB ON NB.ID = E.NatureOfBusiness AND NB.MasterName = 'BusinessNature'
    LEFT JOIN Web_LittleMaster ST ON ST.ID = E.Sourcetype AND ST.MasterName = 'EnquirySourceType'
    LEFT JOIN UserMaster IB ON IB.UserID = E.IntroducedBy
    LEFT JOIN CustomerMaster RC ON RC.CustID = E.ReferredCustID
    LEFT JOIN Web_LittleMaster CM ON CM.ID = E.Campaign AND CM.MasterName = 'Campaign'
    {where}
    ORDER BY E.EnquiryDate DESC
"""


def _row_to_model(r: dict) -> "CustEnquiryRegisterRow":
    return CustEnquiryRegisterRow(
        cust_id=r["CustID"], enquiry_date=r["EnquiryDate"].isoformat() if r["EnquiryDate"] else None,
        stage_percent=float(r["StagePercent"] or 0), received_by=r["ReceivedByName"] or "",
        narration=r["Narration"] or "", segment_name=r["SegmentName"] or "",
        business_nature_name=r["BusinessNatureName"] or "", source_type_name=r["SourceTypeName"] or "",
        source_narration=r["SourceNarration"] or "", introduced_by_name=r["IntroducedByName"] or "",
        referred_by_name=r["ReferredByName"] or "", current_software="", campaign_name=r["CampaignName"] or "",
        case_type=r["CaseType"] or "", hardware_partner=r["HardwarePatner"] or "",
    )


class CustEnquiryRegisterRow(BaseModel):
    cust_id: int
    enquiry_date: str | None
    stage_percent: float
    received_by: str
    narration: str
    segment_name: str
    business_nature_name: str
    source_type_name: str
    source_narration: str
    introduced_by_name: str
    referred_by_name: str
    current_software: str
    campaign_name: str
    case_type: str
    hardware_partner: str


class CustomerRegisterInfo(BaseModel):
    cust_id: int
    shop_name: str
    address: str
    contact_person: str
    mobile_no: str
    tel_no: str
    email: str
    gstin: str
    website_name: str


class EnquiryRegisterSearchResult(BaseModel):
    customer_info: CustomerRegisterInfo | None
    rows: list[CustEnquiryRegisterRow]


class EnquiryRegisterActionRow(BaseModel):
    action_id: int
    action_stage: str
    creation_date: str | None
    creation_time: str
    created_by: str
    action_date: str | None
    action_time: str
    assigned_to: str
    action_description: str
    action_remark: str
    completion_date: str | None
    completion_time: str
    completed_by: str
    completed_remark: str
    sales_person: str
    action_stage_status: str
    quotation_amt: float
    next_action: str


class EnquiryStatusRow(BaseModel):
    assigned_to_user_id: int
    assigned_to: str
    assigned_to_mobile: str
    assigned_to_email: str
    enquiry_count: int
    progress_percent: float
    last_action_date: str | None


class EnquiryStatusDetailRow(BaseModel):
    cust_id: int
    customer_name: str
    segment_name: str
    stage_percent: float
    last_action_date: str | None
    is_auto: bool
    enquiry_date: str | None
    mobile_no: str
    area: str
    city: str


@router.get("/rows", response_model=list[CustEnquiryRegisterRow])
def get_enquiry_register_rows(cust_id: int | None = None) -> list[CustEnquiryRegisterRow]:
    with get_cursor() as cursor:
        if cust_id is not None:
            cursor.execute(_ROWS_SELECT.format(top="", where="WHERE E.CustID = ?"), cust_id)
        else:
            cursor.execute(_ROWS_SELECT.format(top="TOP 500 ", where=""))
        rows = rows_to_dicts(cursor)
    return [_row_to_model(r) for r in rows]


@router.get("/lookup/contact-persons", response_model=list[dict])
def get_contact_person_lookup(search: str = "") -> list[dict]:
    """Mirrors CustEnquiryRegister.aspx.vb's ddlContact source (distinct
    CustomerMaster.Landmark values). Was an unbounded full list — on a table
    this size that's tens of thousands of distinct values shipped and
    rendered up front. Capped to TOP 100 + server-side search instead, same
    load-on-demand shape as every other customer/name picker in this app
    (e.g. this page's own Shop Name picker above)."""
    with get_cursor() as cursor:
        search = search.strip()
        if search:
            # Smart keyword search — see marketing_enquiry.get_customers_for_search.
            keywords = search.split()
            where_clause = " AND ".join(["Landmark LIKE ?"] * len(keywords))
            params = [f"%{kw}%" for kw in keywords]
            cursor.execute(
                "SELECT DISTINCT TOP 100 Landmark AS value, Landmark AS label FROM CustomerMaster "
                f"WHERE Landmark IS NOT NULL AND Landmark <> '' AND {where_clause} ORDER BY Landmark",
                *params,
            )
        else:
            cursor.execute(
                "SELECT DISTINCT TOP 100 Landmark AS value, Landmark AS label FROM CustomerMaster "
                "WHERE Landmark IS NOT NULL AND Landmark <> '' ORDER BY Landmark"
            )
        return rows_to_dicts(cursor)


_CUSTOMER_INFO_SELECT = (
    "SELECT TOP 1 CustID, DisplayName AS ShopName, "
    "ISNULL(FlatNo,'')+ISNULL(Floor,'')+ISNULL(BldgName,'')+ISNULL(Road,'')+','+ISNULL(Area,'')+','+ISNULL(City,'') AS Address, "
    "Landmark AS ContactPerson, MobileNo, PhNo, Email, GSTIN, ARN AS WebsiteName "
    "FROM CustomerMaster WHERE {where}"
)


def _row_to_customer_info(r: dict) -> CustomerRegisterInfo:
    return CustomerRegisterInfo(
        cust_id=r["CustID"], shop_name=r["ShopName"] or "", address=r["Address"] or "",
        contact_person=r["ContactPerson"] or "", mobile_no=r["MobileNo"] or "", tel_no=r["PhNo"] or "",
        email=r["Email"] or "", gstin=r["GSTIN"] or "", website_name=r["WebsiteName"] or "",
    )


@router.get("/customer-info/{cust_id}", response_model=CustomerRegisterInfo | None)
def get_customer_register_info(cust_id: int) -> CustomerRegisterInfo | None:
    """Direct by-ID lookup of the same Customer Information panel /search
    builds — used by pages that already have a resolved CustID (e.g.
    CustEnquiryAction, reached via a "Next Step" drill-down that already
    knows which customer) and just need to display who they're acting on,
    with no search-mode resolution step needed.
    """
    with get_cursor() as cursor:
        cursor.execute(_CUSTOMER_INFO_SELECT.format(where="CustID = ?"), cust_id)
        row = cursor.fetchone()
        if not row:
            return None
        r = dict(zip([c[0] for c in cursor.description], row))
    return _row_to_customer_info(r)


@router.get("/search", response_model=EnquiryRegisterSearchResult)
def search_enquiry_register(mode: str, value: str) -> EnquiryRegisterSearchResult:
    """Mirrors CustEnquiryRegister.aspx.vb's GetFilters()+btnshow_Click: resolve one
    CustID from the selected search mode, then load that customer's info panel and
    their enquiry rows (was `EXEC webproc_showenquiry @CustID, @AutoGenerated` in the
    source — @AutoGenerated is declared but never referenced in the proc body, so it
    has no effect on the result and is safely dropped here).
    """
    where_by_mode = {
        "shop_id": "CustID = ?",
        "cust_id": "CustID = ?",
        "contact_person": "Landmark = ?",
        "gst": "GSTIN = ?",
        "mobile": "(MobileNo = ? OR PhNo LIKE ?)",
    }
    if mode not in where_by_mode:
        return EnquiryRegisterSearchResult(customer_info=None, rows=[])

    select = _CUSTOMER_INFO_SELECT.format(where=where_by_mode[mode])
    with get_cursor() as cursor:
        if mode == "mobile":
            cursor.execute(select, value, f"%{value}%")
        else:
            cursor.execute(select, value)
        row = cursor.fetchone()
        if not row:
            return EnquiryRegisterSearchResult(customer_info=None, rows=[])
        r = dict(zip([c[0] for c in cursor.description], row))
        cust_id = r["CustID"]

        cursor.execute(_ROWS_SELECT.format(top="", where="WHERE E.CustID = ?"), cust_id)
        enquiry_rows = rows_to_dicts(cursor)

    return EnquiryRegisterSearchResult(customer_info=_row_to_customer_info(r), rows=[_row_to_model(er) for er in enquiry_rows])


@router.get("/actions/{cust_id}", response_model=list[EnquiryRegisterActionRow])
def get_enquiry_register_actions(cust_id: int) -> list[EnquiryRegisterActionRow]:
    with get_cursor() as cursor:
        cursor.execute("EXEC webproc_showenquiryaction ?", cust_id)
        rows = rows_to_dicts(cursor)
    return [
        EnquiryRegisterActionRow(
            action_id=r["ActionId"], action_stage=r["ActionStage"] or "",
            creation_date=r["CreationDate"].isoformat() if r["CreationDate"] else None,
            creation_time=str(r["CreationTime"] or ""), created_by=r["CreatedBy"] or "",
            action_date=r["ActionDate"].isoformat() if r["ActionDate"] else None,
            action_time=str(r["ActionTime"] or ""), assigned_to=r["AssignedTo"] or "",
            action_description=r["ActionDescription"] or "", action_remark=r["ActionRemark"] or "",
            completion_date=r["CompletionDate"].isoformat() if r["CompletionDate"] else None,
            completion_time=str(r["CompletionTime"] or ""), completed_by=r["Completedby"] or "",
            completed_remark=r["CompletedRemark"] or "", sales_person=r["SalesPerson"] or "",
            action_stage_status=r["ActionStageStatus"] or "", quotation_amt=float(r["QuotationAmt"] or 0),
            next_action=r["NextAction"] or "",
        )
        for r in rows
    ]


@router.post("/whatsapp/{cust_id}")
def send_whatsapp_message(cust_id: int, message_index: int, mobile_no: str = "") -> dict:
    # Stubbed — see module docstring. Not calling Proc_DripSendWhatsApp for real.
    # mobile_no mirrors the source's editable lblMobile.Text (the actual send target,
    # which may differ from the customer's stored MobileNo) — accepted for interface
    # fidelity even though the send itself stays stubbed.
    return {"success": True}


@router.get("/status", response_model=list[EnquiryStatusRow])
def get_enquiry_status_rows() -> list[EnquiryStatusRow]:
    with get_cursor() as cursor:
        cursor.execute(
            "SELECT AssignedToUserID, AssignedTo, AssignedToMobile, AssignedToEmail, COUNT(*) EnquiryCount, "
            "ROUND(SUM(StagePercent * 1.0) / COUNT(*), 2) ProgressPercent, MAX(LastActionDate) LastActionDate "
            "FROM vwWebEnquiry_Status WHERE StagePercent < 100 "
            "GROUP BY AssignedToUserID, AssignedTo, AssignedToMobile, AssignedToEmail ORDER BY LastActionDate ASC"
        )
        rows = rows_to_dicts(cursor)
    return [
        EnquiryStatusRow(
            assigned_to_user_id=r["AssignedToUserID"] or 0, assigned_to=r["AssignedTo"] or "",
            assigned_to_mobile=r["AssignedToMobile"] or "", assigned_to_email=r["AssignedToEmail"] or "",
            enquiry_count=r["EnquiryCount"] or 0, progress_percent=float(r["ProgressPercent"] or 0),
            last_action_date=r["LastActionDate"].isoformat() if r["LastActionDate"] else None,
        )
        for r in rows
    ]


@router.get("/status/{assigned_to_user_id}", response_model=list[EnquiryStatusDetailRow])
def get_enquiry_status_detail(assigned_to_user_id: int) -> list[EnquiryStatusDetailRow]:
    with get_cursor() as cursor:
        cursor.execute(
            "SELECT CustID, CustomerName, SegmentName, StagePercent, LastActionDate, AutoGenerated, "
            "EnquiryDate, MobileNo, Area, City "
            "FROM vwWebEnquiry_Status WHERE AssignedToUserID = ? AND StagePercent < 100 ORDER BY LastActionDate ASC",
            assigned_to_user_id,
        )
        rows = rows_to_dicts(cursor)
    return [
        EnquiryStatusDetailRow(
            cust_id=r["CustID"], customer_name=r["CustomerName"] or "", segment_name=r["SegmentName"] or "",
            stage_percent=float(r["StagePercent"] or 0),
            last_action_date=r["LastActionDate"].isoformat() if r["LastActionDate"] else None,
            is_auto=bool(r["AutoGenerated"]),
            enquiry_date=r["EnquiryDate"].isoformat() if r["EnquiryDate"] else None,
            mobile_no=r["MobileNo"] or "", area=r["Area"] or "", city=r["City"] or "",
        )
        for r in rows
    ]
